# Generated by Django 2.1.1 on 2018-09-12 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_time', models.DateTimeField(default=datetime.datetime.now)),
                ('input_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=32)),
                ('param_name', models.CharField(max_length=255)),
                ('auc', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1', models.FloatField()),
                ('true_negative', models.IntegerField()),
                ('false_positive', models.IntegerField()),
                ('false_negative', models.IntegerField()),
                ('true_positive', models.IntegerField()),
            ],
        ),
    ]
